# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-split" do
  name "go-split"
  desc "AI-powered Go file splitter - intelligently split large Go files into focused modules"
  homepage "https://github.com/aaronlippold/go-split"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-split"

  on_macos do
    on_intel do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_darwin_amd64.tar.gz"
      sha256 "890313e73538a87188a994bd0f769d780b62a09b3c8e17fb56abebd64d3ec3c3"
    end
    on_arm do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_darwin_arm64.tar.gz"
      sha256 "494c12e94b697b1e834891fd1378ae5056837f3103c9f446ab7e66d104c27210"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_linux_amd64.tar.gz"
      sha256 "14804db4ff94cc7422544b0a3c0af05f62fb28d1b32b17ad1982140ebb03d355"
    end
    on_arm do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_linux_arm64.tar.gz"
      sha256 "daed6da9c537d41b519aa642f08c40a5ee47d8ea4231a2c8bebb043ee5954e6f"
    end
  end

  # No zap stanza required
end
