# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-split" do
  name "go-split"
  desc "AI-powered Go file splitter - intelligently split large Go files into focused modules"
  homepage "https://github.com/aaronlippold/go-split"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-split"

  on_macos do
    on_intel do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_darwin_amd64.tar.gz"
      sha256 "f875198437203a9a02f1fb9478e04517aef6d63bddfa15b511d65d48f8286531"
    end
    on_arm do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_darwin_arm64.tar.gz"
      sha256 "4c4042388e75a87e21b8c4aa31bf76b77435adf61c4555be57bc915d7a28ea46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_linux_amd64.tar.gz"
      sha256 "ef4219d1e351de5c7ddc2b3504b6a0ae47e5e86d98c35986fe2ae9ecd945b158"
    end
    on_arm do
      url "https://github.com/aaronlippold/go-split/releases/download/v#{version}/go-split_#{version}_linux_arm64.tar.gz"
      sha256 "44c127d5217b7377e626c664b295f9ba3773566ba96f5ecd67d6426fb2b20d08"
    end
  end

  # No zap stanza required
end
