# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSplit < Formula
  desc "AI-powered Go file splitter - intelligently split large Go files into focused modules"
  homepage "https://github.com/aaronlippold/go-split"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaronlippold/go-split/releases/download/v0.1.0/go-split_0.1.0_darwin_amd64.tar.gz"
      sha256 "ae28fd24dbe2a2b96b6f308a76063f46c3ace15baff3850df6216e6c0af1ad97"

      def install
        bin.install "go-split"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaronlippold/go-split/releases/download/v0.1.0/go-split_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1fc5b60ee2eee0038274b3f4c82d591928df56e68d6346fd7a898fce7a80df7"

      def install
        bin.install "go-split"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronlippold/go-split/releases/download/v0.1.0/go-split_0.1.0_linux_amd64.tar.gz"
      sha256 "da5170964a767099c16705f786259a1a050c6ae496bd4f75d3f21f1ea859903a"
      def install
        bin.install "go-split"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaronlippold/go-split/releases/download/v0.1.0/go-split_0.1.0_linux_arm64.tar.gz"
      sha256 "d83040f8f8487f541de6b425a7c698e90db46fd838770a0ab866cfac57a8c282"
      def install
        bin.install "go-split"
      end
    end
  end

  test do
    system "#{bin}/go-split", "--version"
  end
end
